apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-server
        tier: service
    spec:
      containers:
      - name: node-server
        image: "node-server:1.0.1"
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        
        # define resource requests and limits
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "125m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "250m"

        # for faster SIGKILL shutdown
        # terminationGracePeriodSeconds: 5
        
        # check of node-server is alive and healthy
        # readinessProbe:
        #   httpGet:
        #     path: /ping
        #     port: 9090
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        # livenessProbe:
        #   httpGet:
        #     path: /ping
        #     port: 9090
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5       
        